services:
  black-delta:
    build: .
    container_name: black-delta
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1
