services:
  pulse:
    build: .
    container_name: pulse-bot
    restart: unless-stopped
    ports:
      - "8888:8888"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    dns:
      - 8.8.8.8
      - 1.1.1.1
